GRANT ALL ON DATABASE sem2024_mateov TO tianl WITH GRANT OPTION;
GRANT ALL ON SCHEMA public TO tianl WITH GRANT OPTION;
GRANT ALL ON ALL TABLES IN SCHEMA public TO tianl WITH GRANT OPTION;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO tianl WITH GRANT OPTION;

GRANT CONNECT ON DATABAateov TO javnost;
########################################################################

GRANT ALL PRIVILEGES ON DATABAateov TO javnost;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO javnost;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO javnost;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO javnost;

GRANT ALL PRIVILEGES ON DATABAateov TO tianl;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO tianl;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO tianl;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO tianl;


--prihodnje pravice
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO tianl;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO tianl;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO tianl;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO javnost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO javnost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO javnost;

-- javnost ne sme spreminjat tabel
REVOKE CREATE ON SCHEMA public FROM javnost;